-- Shops
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'sharma-grocery',
  'Sharma Grocery Store',
  'grocery',
  'Grocery & Household',
  4.7,
  486,
  0.8,
  '0.8 km',
  'Jayadev Vihar',
  'Plot 142, IRC Village Road, Jayadev Vihar, Bhubaneswar',
  '25–35 min',
  20,
  true,
  'Open · Closes 9:30 PM',
  '9:30 PM',
  520,
  100,
  true,
  'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
  'Serving the Jayadev Vihar community for over 18 years. Best quality daily grocery staples, authentic spices, cold-pressed oils, and household goods at honest neighborhood prices.',
  'Ramesh Sharma',
  '+91 94370 12345',
  '{"Verified Local","Instant UPI","Doorstep Delivery","Fresh Stock"}'::text[],
  '{"All","Grocery","Dairy & Bread","Beverages","Snacks","Household"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'maa-laxmi',
  'Maa Laxmi General Store',
  'grocery',
  'Grocery & Household',
  4.8,
  342,
  1.2,
  '1.2 km away',
  'Saheed Nagar',
  'Shop 18, Commercial Complex, Saheed Nagar, Bhubaneswar',
  '20–30 min',
  15,
  true,
  'Open · Closes 10:00 PM',
  '10:00 PM',
  360,
  80,
  true,
  'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  'A trusted family-run neighborhood shop offering premium pulses, rice, packaged dry fruits, gourmet biscuits, and daily domestic essentials.',
  'Subrat Mohanty',
  '+91 98612 87654',
  '{"Verified Local","350+ Products","Fast Delivery"}'::text[],
  '{"All","Grocery","Snacks","Household","Personal Care"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'fresh-basket',
  'Fresh Basket Organics',
  'fruits & vegetables',
  'Fresh Fruits & Farm Produce',
  4.9,
  624,
  1.5,
  '1.5 km',
  'Patia',
  'Near KIIT Campus 6 Road, Patia, Bhubaneswar',
  '20–30 min',
  25,
  true,
  'Open · Closes 8:30 PM',
  '8:30 PM',
  225,
  150,
  true,
  'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  'Direct farm sourced fresh seasonal vegetables, exotic salad greens, fresh herbs, and hand-picked orchard fruits. Washed and hygienically packaged.',
  'Priyadarshi Sahoo',
  '+91 99371 45678',
  '{"Organic Produce","Farm Direct","Chemical Free"}'::text[],
  '{"All","Daily Veggies","Exotic Fruits","Herbs & Greens"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'city-bakery',
  'City Bakery & Confectionery',
  'bakery',
  'Artisan Bakery & Fresh Bakes',
  4.6,
  418,
  2.4,
  '2.4 km',
  'Master Canteen',
  'Station Square, Master Canteen, Bhubaneswar',
  '30–40 min',
  25,
  true,
  'Open · Closes 10:30 PM',
  '10:30 PM',
  185,
  100,
  false,
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  'Oven fresh breads, soft sandwich loaves, puffs, authentic cookies, milk cakes, and handcrafted celebration cakes made with pure butter.',
  'Bikash Tripathy',
  '+91 93380 99887',
  '{"Oven Fresh","Artisan","Freshly Baked"}'::text[],
  '{"All","Breads","Cakes & Pastries","Cookies","Savouries"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'apna-pharmacy',
  'Apna Pharmacy & Surgicals',
  'pharmacy',
  'Medicines & Health',
  4.9,
  532,
  0.6,
  '0.6 km',
  'Jayadev Vihar',
  'Lane 3, Biju Patnaik College Road, Jayadev Vihar, Bhubaneswar',
  '15–25 min',
  10,
  true,
  'Open · Closes 11:00 PM',
  '11:00 PM',
  840,
  50,
  true,
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
  'Licensed neighborhood pharmacy stocked with genuine OTC healthcare essentials, fever relief, multivitamins, baby food, and medical supplies.',
  'Dr. Alok Nayak (Pharm)',
  '+91 94372 33445',
  '{"100% Genuine","Licensed","Fastest Delivery"}'::text[],
  '{"All","Medicines","Wellness","First Aid","Baby Care"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'odisha-stationery',
  'Odisha Stationery & Book House',
  'stationery',
  'Stationery & School Supplies',
  4.7,
  295,
  2,
  '2.0 km',
  'Chandrasekharpur',
  'Opposite Petrol Pump, Damana Square, Chandrasekharpur, Bhubaneswar',
  '25–35 min',
  20,
  true,
  'Open · Closes 9:00 PM',
  '9:00 PM',
  410,
  80,
  false,
  'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1507842229451-79b1be886a20?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
  'School notebooks, premium pens, art supplies, office folders, calculation tools, and engineering drawing sets for students and professionals.',
  'Manas Jena',
  '+91 98619 55667',
  '{"Student Friendly","School Supplies","Bulk Stationery"}'::text[],
  '{"All","Notebooks","Pens & Pencils","Art & Craft","Office Supplies"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'kumar-electronics',
  'Kumar Electronics & Mobiles',
  'electronics',
  'Electronics & Accessories',
  4.5,
  189,
  3.1,
  '3.1 km',
  'Nayapalli',
  'Near ISKCON Temple, Nayapalli, Bhubaneswar',
  '35–45 min',
  30,
  true,
  'Open · Closes 9:30 PM',
  '9:30 PM',
  160,
  200,
  false,
  'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
  'Original mobile phone chargers, Type-C cables, wired & wireless earphones, power banks, extension boards, and everyday tech gadgets.',
  'Santosh Kumar',
  '+91 97760 11223',
  '{"Brand Warranty","Original Goods","Tech Support"}'::text[],
  '{"All","Cables & Adapters","Audio","Power","Accessories"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'khandagiri-sweets',
  'Khandagiri Sweets & Chaat',
  'restaurants',
  'Traditional Sweets & Snacks',
  4.8,
  760,
  3.5,
  '3.5 km',
  'Khandagiri',
  'Square Junction, Near Caves Entrance, Khandagiri, Bhubaneswar',
  '25–35 min',
  25,
  false,
  'Closed · Opens 4:00 PM',
  '10:30 PM',
  120,
  100,
  false,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
  'Famous for traditional Odisha Chhena Poda, Rasagola, hot samosas, dahi vada aloo dum, and evening street chaat treats.',
  'Debasis Das',
  '+91 94388 77665',
  '{"Authentic Odia","Famous Chaat","Freshly Cooked"}'::text[],
  '{"All","Traditional Sweets","Evening Snacks","Chaat Special"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'sum-medico',
  'SUM Medico & Healthcare',
  'pharmacy',
  'Pharmacy & Patient Care',
  4.9,
  428,
  3.8,
  '3.8 km',
  'SUM Hospital, Kalinga Nagar',
  'Opposite Gate No. 2, IMS & SUM Hospital Road, Kalinga Nagar, Bhubaneswar',
  '20–30 min',
  20,
  true,
  'Open 24 Hours · Immediate Delivery',
  'Open 24x7',
  650,
  50,
  true,
  'https://images.unsplash.com/photo-1586015555751-63c299c855a8?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=200&q=80',
  'Serving IMS & SUM Hospital campus, doctors, medical staff, patients, and Kalinga Nagar residents 24x7. Stocked with genuine emergency medications, surgical items, baby nutrition, and wellness essentials.',
  'Debabrata Samantray',
  '+91 94371 88990',
  '{"24x7 Available","Opposite SUM Hospital","Emergency Care","Doctor Trusted"}'::text[],
  '{"All","Medicines","Wellness","Patient Care","Baby Nutrition"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

