INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'fresh-bananas-dozen',
  'fresh-basket',
  'Robusta Golden Bananas',
  'Farm Fresh',
  '1 Dozen (12 Pcs)',
  65,
  75,
  13,
  'fruits-veg',
  'Daily Veggies',
  true,
  4.8,
  118,
  true,
  'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
  'Naturally ripened sweet bananas packed with potassium, instant natural energy, and dietary fibers.',
  '{"Ripening":"100% Naturally Ripened without Carbide","Count":"12 Units"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'sandwich-bread-400g',
  'city-bakery',
  'Artisan Whole Milk Sandwich Bread',
  'City Bakes',
  '400 g',
  45,
  45,
  0,
  'bakery',
  'Breads',
  true,
  4.7,
  84,
  true,
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
  'Freshly baked morning loaf with soft crumb and thin golden crust. Perfect for butter toast, grilled sandwiches, and French toast.',
  '{"Baked Time":"6:00 AM Today","Contains":"Pure Milk & Butter"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'choco-truffle-pastry',
  'city-bakery',
  'Belgian Dark Chocolate Truffle Pastry',
  'City Bakes',
  '2 Pcs Pack',
  150,
  170,
  12,
  'bakery',
  'Cakes & Pastries',
  true,
  4.9,
  96,
  true,
  'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
  'Decadent layered dark chocolate sponge infused with rich Dutch ganache and topped with silky chocolate curls.',
  '{"Vegetarian":"100% Eggless","Serving":"2 Portions"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'dolo-650-strip',
  'apna-pharmacy',
  'Dolo 650mg Paracetamol Tablets',
  'Micro Labs',
  '15 Tablets (1 Strip)',
  32,
  32,
  0,
  'pharmacy',
  'Medicines',
  true,
  4.9,
  310,
  true,
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
  'Trusted fever and mild-to-moderate pain reliever. Fast action paracetamol formulation for headache, body ache, and viral symptoms.',
  '{"Composition":"Paracetamol IP 650mg","Dosage":"As prescribed by physician"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'vicks-vaporub-50ml',
  'apna-pharmacy',
  'Vicks VapoRub Relief Balm',
  'Procter & Gamble',
  '50 ml',
  145,
  155,
  6,
  'pharmacy',
  'Wellness',
  true,
  4.8,
  175,
  false,
  'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80',
  'Provides relief from 6 cough & cold symptoms including blocked nose, headache, and muscle stiffness with natural eucalyptus & camphor.',
  '{"Active Oils":"Camphor, Menthol, Eucalyptus Oil","Form":"Ointment"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'classmate-notebook-pack',
  'odisha-stationery',
  'Classmate Long Single Line Notebooks',
  'ITC Classmate',
  '172 Pages (Pack of 3)',
  195,
  210,
  7,
  'stationery',
  'Notebooks',
  true,
  4.8,
  88,
  true,
  'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
  'Premium elemental chlorine-free eco-friendly smooth writing paper. High opacity ensures no ink bleed through.',
  '{"Binding":"Center Stapled","Ruling":"Single Line Ruled"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'boat-bassheads-100',
  'kumar-electronics',
  'boAt BassHeads 100 In-Ear Wired Earphones',
  'boAt',
  '1 Unit (with Mic)',
  399,
  999,
  60,
  'electronics',
  'Audio',
  true,
  4.4,
  240,
  true,
  'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
  'Super extra bass with 10mm dynamic drivers. Hawk-inspired metallic finish, tangle-resistant cord, and HD clear inline microphone.',
  '{"Driver":"10mm Dynamic","Jack":"3.5mm Gold Plated","Warranty":"1 Year Official Brand Warranty"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'type-c-fast-cable',
  'kumar-electronics',
  'Portronics 65W Fast Charging Type-C Cable',
  'Portronics',
  '1.2 Meter (Nylon Braided)',
  199,
  399,
  50,
  'electronics',
  'Cables & Adapters',
  true,
  4.6,
  110,
  false,
  'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
  'Heavy duty nylon braided copper wire supporting up to 65W fast power delivery and high-speed data transmission up to 480 Mbps.',
  '{"Current Output":"Up to 3.5A Fast Charge","Durability":"10000+ Bend Tested"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'chhena-poda-fresh',
  'khandagiri-sweets',
  'Traditional Odisha Chhena Poda (Baked Cottage Cheese)',
  'Khandagiri Heritage',
  '500 g',
  190,
  200,
  5,
  'restaurants',
  'Traditional Sweets',
  true,
  4.9,
  340,
  true,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
  'Authentic Odia dessert made by slow baking fresh cottage cheese, caramelized sugar, cardamom, and roasted cashews. Soft interior with aromatic caramelized brown crust.',
  '{"Specialty":"State Sweet of Odisha","Shelf Life":"3 Days"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'volini-pain-spray-100g',
  'sum-medico',
  'Volini Instant Pain Relief Spray',
  'Sun Pharma',
  '100 g',
  165,
  185,
  11,
  'pharmacy',
  'Medicines',
  true,
  4.8,
  195,
  true,
  'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80',
  'Micro-particles formula for quick penetration and fast relief from joint pain, lower back pain, sprains, and sports muscle strains.',
  '{"Active Salt":"Diclofenac Diethylamine, Methyl Salicylate, Menthol","Form":"Aerosol Spray"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'pediasure-vanilla-400g',
  'sum-medico',
  'PediaSure 7+ Complete Nutrition Drink (Vanilla)',
  'Abbott',
  '400 g',
  395,
  430,
  8,
  'pharmacy',
  'Baby Nutrition',
  true,
  4.9,
  160,
  true,
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
  'Scientifically formulated with 37 vital nutrients, prebiotics, and zinc to support growing children''s immunity, bone health, and height gain.',
  '{"Flavor":"Classic Vanilla","Nutrients":"37 Vital Growth Nutrients"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'accu-chek-active-glucometer',
  'sum-medico',
  'Accu-Chek Active Blood Glucose Monitor Kit',
  'Roche',
  '1 Unit (with 10 Strips & Lancets)',
  899,
  1299,
  30,
  'pharmacy',
  'Patient Care',
  true,
  4.9,
  220,
  true,
  'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80',
  'Accurate, easy-to-use blood glucose monitoring system providing accurate readings in just 5 seconds. Doctor recommended for home and clinic care.',
  '{"Test Time":"5 Seconds","Warranty":"Lifetime Manufacturer Warranty"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;

INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'dettol-sanitizer-500ml',
  'sum-medico',
  'Dettol Instant Germ Protection Hand Sanitizer Pump',
  'Dettol',
  '500 ml',
  195,
  225,
  13,
  'pharmacy',
  'Wellness',
  true,
  4.8,
  140,
  false,
  'https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=600&q=80',
  'Kills 99.9% of illness-causing germs without soap or water. Non-sticky formula enriched with moisturizers and fresh fragrance.',
  '{"Alcohol Content":"72% v/v","Format":"Pump Dispenser Bottle"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
