-- Seed data for LocalStore

-- Categories
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('grocery', 'Grocery', 'Grocery & Staples', 'ShoppingBag', 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80', 'Daily grains, pulses, spices, oils and household staples')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('fruits-veg', 'Fruits & Vegetables', 'Fruits & Veggies', 'Apple', 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=600&q=80', 'Fresh farm produce picked and delivered daily')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('bakery', 'Bakery', 'Bakery & Dairy', 'Croissant', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80', 'Artisan breads, milk, fresh paneer, cakes and sweet treats')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('pharmacy', 'Pharmacy', 'Pharmacy & Care', 'Pill', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80', 'Prescription medicines, wellness, OTC care and first aid')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('electronics', 'Electronics', 'Electronics', 'Smartphone', 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80', 'Cables, chargers, audio, batteries and home appliances')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('fashion', 'Fashion', 'Fashion & Apparel', 'Shirt', 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80', 'Local apparel, handloom weaves, cotton casuals and accessories')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('stationery', 'Stationery', 'Stationery & Books', 'BookOpen', 'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=600&q=80', 'School supplies, notebooks, stationery sets and office essentials')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('household', 'Household', 'Home Essentials', 'Home', 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80', 'Cleaning liquids, kitchen utensils, storage and bathroom supplies')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('beauty', 'Beauty', 'Beauty & Grooming', 'Sparkles', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80', 'Haircare, skincare, natural soaps and personal grooming')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('hardware', 'Hardware', 'Hardware & Tools', 'Wrench', 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=600&q=80', 'Electrical switches, bulbs, repair tapes, glues and basic tools')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('restaurants', 'Restaurants', 'Sweets & Snacks', 'Utensils', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80', 'Traditional Odia sweets, fresh hot chaat, samosas and tea')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;
INSERT INTO public.categories (id, name, label, icon, image, description)
VALUES ('other', 'Other', 'Local Specialty', 'Store', 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=600&q=80', 'Pet supplies, gardening seeds, puja samagri and unique local finds')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  label = EXCLUDED.label,
  icon = EXCLUDED.icon,
  image = EXCLUDED.image,
  description = EXCLUDED.description;

-- Localities
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('jayadev-vihar', 'Jayadev Vihar', 'Near Pal Heights', 'Current location')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('sum-hospital', 'SUM Hospital', 'Kalinga Nagar / Ghatikia', '3.8 km away')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('patia', 'Patia', 'Near KIIT Square', '4.2 km away')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('saheed-nagar', 'Saheed Nagar', 'Near Sparsh Hospital', '2.8 km away')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('khandagiri', 'Khandagiri', 'Near Udayagiri Caves', '5.1 km away')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('chandrasekharpur', 'Chandrasekharpur', 'Near Damana Square', '3.5 km away')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('master-canteen', 'Master Canteen', 'Railway Station Road', '3.9 km away')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('nayapalli', 'Nayapalli', 'Near IRC Village', '1.6 km away')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;
INSERT INTO public.localities (id, name, landmark, distance_text)
VALUES ('old-town', 'Old Town', 'Near Lingaraj Temple', '6.8 km away')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  landmark = EXCLUDED.landmark,
  distance_text = EXCLUDED.distance_text;

-- Shops
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'sharma-grocery',
  'Sharma Grocery Store',
  'grocery',
  'Grocery & Household',
  4.7,
  486,
  0.8,
  '0.8 km',
  'Jayadev Vihar',
  'Plot 142, IRC Village Road, Jayadev Vihar, Bhubaneswar',
  '25–35 min',
  20,
  true,
  'Open · Closes 9:30 PM',
  '9:30 PM',
  520,
  100,
  true,
  'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
  'Serving the Jayadev Vihar community for over 18 years. Best quality daily grocery staples, authentic spices, cold-pressed oils, and household goods at honest neighborhood prices.',
  'Ramesh Sharma',
  '+91 94370 12345',
  '{"Verified Local","Instant UPI","Doorstep Delivery","Fresh Stock"}'::text[],
  '{"All","Grocery","Dairy & Bread","Beverages","Snacks","Household"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'maa-laxmi',
  'Maa Laxmi General Store',
  'grocery',
  'Grocery & Household',
  4.8,
  342,
  1.2,
  '1.2 km away',
  'Saheed Nagar',
  'Shop 18, Commercial Complex, Saheed Nagar, Bhubaneswar',
  '20–30 min',
  15,
  true,
  'Open · Closes 10:00 PM',
  '10:00 PM',
  360,
  80,
  true,
  'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  'A trusted family-run neighborhood shop offering premium pulses, rice, packaged dry fruits, gourmet biscuits, and daily domestic essentials.',
  'Subrat Mohanty',
  '+91 98612 87654',
  '{"Verified Local","350+ Products","Fast Delivery"}'::text[],
  '{"All","Grocery","Snacks","Household","Personal Care"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'fresh-basket',
  'Fresh Basket Organics',
  'fruits & vegetables',
  'Fresh Fruits & Farm Produce',
  4.9,
  624,
  1.5,
  '1.5 km',
  'Patia',
  'Near KIIT Campus 6 Road, Patia, Bhubaneswar',
  '20–30 min',
  25,
  true,
  'Open · Closes 8:30 PM',
  '8:30 PM',
  225,
  150,
  true,
  'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  'Direct farm sourced fresh seasonal vegetables, exotic salad greens, fresh herbs, and hand-picked orchard fruits. Washed and hygienically packaged.',
  'Priyadarshi Sahoo',
  '+91 99371 45678',
  '{"Organic Produce","Farm Direct","Chemical Free"}'::text[],
  '{"All","Daily Veggies","Exotic Fruits","Herbs & Greens"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'city-bakery',
  'City Bakery & Confectionery',
  'bakery',
  'Artisan Bakery & Fresh Bakes',
  4.6,
  418,
  2.4,
  '2.4 km',
  'Master Canteen',
  'Station Square, Master Canteen, Bhubaneswar',
  '30–40 min',
  25,
  true,
  'Open · Closes 10:30 PM',
  '10:30 PM',
  185,
  100,
  false,
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  'Oven fresh breads, soft sandwich loaves, puffs, authentic cookies, milk cakes, and handcrafted celebration cakes made with pure butter.',
  'Bikash Tripathy',
  '+91 93380 99887',
  '{"Oven Fresh","Artisan","Freshly Baked"}'::text[],
  '{"All","Breads","Cakes & Pastries","Cookies","Savouries"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'apna-pharmacy',
  'Apna Pharmacy & Surgicals',
  'pharmacy',
  'Medicines & Health',
  4.9,
  532,
  0.6,
  '0.6 km',
  'Jayadev Vihar',
  'Lane 3, Biju Patnaik College Road, Jayadev Vihar, Bhubaneswar',
  '15–25 min',
  10,
  true,
  'Open · Closes 11:00 PM',
  '11:00 PM',
  840,
  50,
  true,
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
  'Licensed neighborhood pharmacy stocked with genuine OTC healthcare essentials, fever relief, multivitamins, baby food, and medical supplies.',
  'Dr. Alok Nayak (Pharm)',
  '+91 94372 33445',
  '{"100% Genuine","Licensed","Fastest Delivery"}'::text[],
  '{"All","Medicines","Wellness","First Aid","Baby Care"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'odisha-stationery',
  'Odisha Stationery & Book House',
  'stationery',
  'Stationery & School Supplies',
  4.7,
  295,
  2,
  '2.0 km',
  'Chandrasekharpur',
  'Opposite Petrol Pump, Damana Square, Chandrasekharpur, Bhubaneswar',
  '25–35 min',
  20,
  true,
  'Open · Closes 9:00 PM',
  '9:00 PM',
  410,
  80,
  false,
  'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1507842229451-79b1be886a20?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
  'School notebooks, premium pens, art supplies, office folders, calculation tools, and engineering drawing sets for students and professionals.',
  'Manas Jena',
  '+91 98619 55667',
  '{"Student Friendly","School Supplies","Bulk Stationery"}'::text[],
  '{"All","Notebooks","Pens & Pencils","Art & Craft","Office Supplies"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'kumar-electronics',
  'Kumar Electronics & Mobiles',
  'electronics',
  'Electronics & Accessories',
  4.5,
  189,
  3.1,
  '3.1 km',
  'Nayapalli',
  'Near ISKCON Temple, Nayapalli, Bhubaneswar',
  '35–45 min',
  30,
  true,
  'Open · Closes 9:30 PM',
  '9:30 PM',
  160,
  200,
  false,
  'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
  'Original mobile phone chargers, Type-C cables, wired & wireless earphones, power banks, extension boards, and everyday tech gadgets.',
  'Santosh Kumar',
  '+91 97760 11223',
  '{"Brand Warranty","Original Goods","Tech Support"}'::text[],
  '{"All","Cables & Adapters","Audio","Power","Accessories"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'khandagiri-sweets',
  'Khandagiri Sweets & Chaat',
  'restaurants',
  'Traditional Sweets & Snacks',
  4.8,
  760,
  3.5,
  '3.5 km',
  'Khandagiri',
  'Square Junction, Near Caves Entrance, Khandagiri, Bhubaneswar',
  '25–35 min',
  25,
  false,
  'Closed · Opens 4:00 PM',
  '10:30 PM',
  120,
  100,
  false,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
  'Famous for traditional Odisha Chhena Poda, Rasagola, hot samosas, dahi vada aloo dum, and evening street chaat treats.',
  'Debasis Das',
  '+91 94388 77665',
  '{"Authentic Odia","Famous Chaat","Freshly Cooked"}'::text[],
  '{"All","Traditional Sweets","Evening Snacks","Chaat Special"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'sum-medico',
  'SUM Medico & Healthcare',
  'pharmacy',
  'Pharmacy & Patient Care',
  4.9,
  428,
  3.8,
  '3.8 km',
  'SUM Hospital, Kalinga Nagar',
  'Opposite Gate No. 2, IMS & SUM Hospital Road, Kalinga Nagar, Bhubaneswar',
  '20–30 min',
  20,
  true,
  'Open 24 Hours · Immediate Delivery',
  'Open 24x7',
  650,
  50,
  true,
  'https://images.unsplash.com/photo-1586015555751-63c299c855a8?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=200&q=80',
  'Serving IMS & SUM Hospital campus, doctors, medical staff, patients, and Kalinga Nagar residents 24x7. Stocked with genuine emergency medications, surgical items, baby nutrition, and wellness essentials.',
  'Debabrata Samantray',
  '+91 94371 88990',
  '{"24x7 Available","Opposite SUM Hospital","Emergency Care","Doctor Trusted"}'::text[],
  '{"All","Medicines","Wellness","Patient Care","Baby Nutrition"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

-- Products
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'amul-taaza-1l',
  'sharma-grocery',
  'Amul Taaza Homogenised Toned Milk',
  'Amul',
  '1 L',
  62,
  62,
  0,
  'grocery',
  'Dairy & Bread',
  true,
  4.8,
  142,
  true,
  'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80',
  'Freshly packed toned milk with 3.0% fat and 8.5% SNF. Excellent for daily tea, coffee, breakfast cereal, and homemade paneer. Delivered in chilled condition.',
  '{"Type":"Pasteurised & Homogenised Toned Milk","Shelf Life":"2 Days from dispatch","Storage":"Keep refrigerated below 4°C","FSSAI License":"10012021000071"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'amul-butter-500g',
  'sharma-grocery',
  'Amul Pasteurised Salted Butter',
  'Amul',
  '500 g',
  275,
  290,
  5,
  'grocery',
  'Dairy & Bread',
  true,
  4.9,
  88,
  true,
  'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80',
  'India''s favorite golden butter made from pure milk fat. Adds rich flavor to warm rotis, toasts, parathas, and baking recipes.',
  '{"Key Ingredients":"Butter, Common Salt, Permitted Natural Color","Shelf Life":"12 Months","Storage":"Keep under refrigeration"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'aashirvaad-atta-5kg',
  'sharma-grocery',
  'Aashirvaad Shudh Whole Wheat Chakki Atta',
  'Aashirvaad',
  '5 kg',
  245,
  270,
  9,
  'grocery',
  'Grocery',
  true,
  4.8,
  210,
  true,
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
  '100% pure whole wheat ground with modern chakki process to preserve dietary fibers and vital nutrients for soft, fluffy rotis that stay soft longer.',
  '{"Type":"Whole Wheat Flour","Fiber Content":"High","Origin":"Madhya Pradesh MP Wheat"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'tata-salt-1kg',
  'sharma-grocery',
  'Tata Salt Vacuum Evaporated Iodised',
  'Tata',
  '1 kg',
  28,
  28,
  0,
  'grocery',
  'Grocery',
  true,
  4.9,
  320,
  false,
  'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
  'Desh ka Namak. Pure vacuum-evaporated iodised cooking salt essential for balanced nutrition and daily cooking.',
  '{"Nutrient":"Iodine Enriched","Purity":"99.9% Pure"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'fortune-sunflower-oil-1l',
  'sharma-grocery',
  'Fortune Sunlite Refined Sunflower Oil Pouch',
  'Fortune',
  '1 L',
  142,
  165,
  14,
  'grocery',
  'Grocery',
  true,
  4.6,
  95,
  true,
  'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
  'Light, healthy, fortified with Vitamin A & D. Low absorption formula keeps fried snacks crispy without feeling greasy.',
  '{"Vitamins":"A, D, E","Fat Content":"Zero Cholesterol"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'daawat-basmati-5kg',
  'maa-laxmi',
  'Daawat Rozana Super Basmati Rice',
  'Daawat',
  '5 kg',
  449,
  499,
  10,
  'grocery',
  'Grocery',
  true,
  4.7,
  164,
  true,
  'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
  'Aromatic slender grains naturally aged to perfection. Perfect grain elongation and fluffiness for daily meals, pulao, and khichdi.',
  '{"Grain Length":"Extra Long","Aging":"Aged for 1 year"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'tata-toor-dal-1kg',
  'maa-laxmi',
  'Tata Sampann Unpolished Toor Dal',
  'Tata Sampann',
  '1 kg',
  165,
  185,
  11,
  'grocery',
  'Grocery',
  true,
  4.8,
  130,
  true,
  'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
  'Unpolished arhar/toor dal without water or leather polishing. Retains wholesome natural taste and high protein goodness.',
  '{"Polish":"Unpolished (No chemical polishing)","Protein":"22g per 100g"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'maggi-masala-4pack',
  'maa-laxmi',
  'Maggi 2-Minute Special Masala Noodles',
  'Nestle',
  '280 g (4 Packs)',
  56,
  60,
  7,
  'grocery',
  'Snacks',
  true,
  4.9,
  420,
  true,
  'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80',
  'Classic blend of 20 spices and herbs. Quick comfort meal ready in just 2 minutes for tea time or late-night cravings.',
  '{"Servings":"4 portions","Flavor":"Authentic Masala"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'parle-g-gold-1kg',
  'maa-laxmi',
  'Parle-G Gold Glucose Biscuits Big Pack',
  'Parle',
  '1 kg',
  115,
  125,
  8,
  'grocery',
  'Snacks',
  true,
  4.9,
  380,
  true,
  'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80',
  'Richer, crunchier Parle-G Gold made with milk and wheat. Perfect companion for your morning cup of hot chai.',
  '{"Ingredients":"Wheat Flour, Sugar, Invert Sugar Syrup, Milk Solids","Pack Type":"Family Value Pack"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'shimla-apple-1kg',
  'fresh-basket',
  'Crisp Shimla Royal Delicious Apples',
  'Farm Fresh',
  '1 kg (4–5 Pcs)',
  179,
  210,
  15,
  'fruits-veg',
  'Exotic Fruits',
  true,
  4.7,
  92,
  true,
  'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
  'Crispy sweet red apples directly sourced from Kinnaur & Shimla high altitude orchards. Naturally sweet, firm flesh and rich in antioxidants.',
  '{"Origin":"Himachal Pradesh","Quality":"Grade A Hand-sorted"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'fresh-tomatoes-1kg',
  'fresh-basket',
  'Fresh Hybrid Red Tomatoes',
  'Farm Fresh',
  '1 kg',
  38,
  45,
  15,
  'fruits-veg',
  'Daily Veggies',
  true,
  4.6,
  150,
  true,
  'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
  'Firm, juicy, vine-ripened red tomatoes ideal for curries, gravies, fresh salads, and everyday dal tadka.',
  '{"Sourced":"Local Odisha Farmers","Freshness":"Picked within 24 hours"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'fresh-bananas-dozen',
  'fresh-basket',
  'Robusta Golden Bananas',
  'Farm Fresh',
  '1 Dozen (12 Pcs)',
  65,
  75,
  13,
  'fruits-veg',
  'Daily Veggies',
  true,
  4.8,
  118,
  true,
  'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
  'Naturally ripened sweet bananas packed with potassium, instant natural energy, and dietary fibers.',
  '{"Ripening":"100% Naturally Ripened without Carbide","Count":"12 Units"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'sandwich-bread-400g',
  'city-bakery',
  'Artisan Whole Milk Sandwich Bread',
  'City Bakes',
  '400 g',
  45,
  45,
  0,
  'bakery',
  'Breads',
  true,
  4.7,
  84,
  true,
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
  'Freshly baked morning loaf with soft crumb and thin golden crust. Perfect for butter toast, grilled sandwiches, and French toast.',
  '{"Baked Time":"6:00 AM Today","Contains":"Pure Milk & Butter"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'choco-truffle-pastry',
  'city-bakery',
  'Belgian Dark Chocolate Truffle Pastry',
  'City Bakes',
  '2 Pcs Pack',
  150,
  170,
  12,
  'bakery',
  'Cakes & Pastries',
  true,
  4.9,
  96,
  true,
  'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
  'Decadent layered dark chocolate sponge infused with rich Dutch ganache and topped with silky chocolate curls.',
  '{"Vegetarian":"100% Eggless","Serving":"2 Portions"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'dolo-650-strip',
  'apna-pharmacy',
  'Dolo 650mg Paracetamol Tablets',
  'Micro Labs',
  '15 Tablets (1 Strip)',
  32,
  32,
  0,
  'pharmacy',
  'Medicines',
  true,
  4.9,
  310,
  true,
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
  'Trusted fever and mild-to-moderate pain reliever. Fast action paracetamol formulation for headache, body ache, and viral symptoms.',
  '{"Composition":"Paracetamol IP 650mg","Dosage":"As prescribed by physician"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'vicks-vaporub-50ml',
  'apna-pharmacy',
  'Vicks VapoRub Relief Balm',
  'Procter & Gamble',
  '50 ml',
  145,
  155,
  6,
  'pharmacy',
  'Wellness',
  true,
  4.8,
  175,
  false,
  'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80',
  'Provides relief from 6 cough & cold symptoms including blocked nose, headache, and muscle stiffness with natural eucalyptus & camphor.',
  '{"Active Oils":"Camphor, Menthol, Eucalyptus Oil","Form":"Ointment"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'classmate-notebook-pack',
  'odisha-stationery',
  'Classmate Long Single Line Notebooks',
  'ITC Classmate',
  '172 Pages (Pack of 3)',
  195,
  210,
  7,
  'stationery',
  'Notebooks',
  true,
  4.8,
  88,
  true,
  'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
  'Premium elemental chlorine-free eco-friendly smooth writing paper. High opacity ensures no ink bleed through.',
  '{"Binding":"Center Stapled","Ruling":"Single Line Ruled"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'boat-bassheads-100',
  'kumar-electronics',
  'boAt BassHeads 100 In-Ear Wired Earphones',
  'boAt',
  '1 Unit (with Mic)',
  399,
  999,
  60,
  'electronics',
  'Audio',
  true,
  4.4,
  240,
  true,
  'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
  'Super extra bass with 10mm dynamic drivers. Hawk-inspired metallic finish, tangle-resistant cord, and HD clear inline microphone.',
  '{"Driver":"10mm Dynamic","Jack":"3.5mm Gold Plated","Warranty":"1 Year Official Brand Warranty"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'type-c-fast-cable',
  'kumar-electronics',
  'Portronics 65W Fast Charging Type-C Cable',
  'Portronics',
  '1.2 Meter (Nylon Braided)',
  199,
  399,
  50,
  'electronics',
  'Cables & Adapters',
  true,
  4.6,
  110,
  false,
  'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
  'Heavy duty nylon braided copper wire supporting up to 65W fast power delivery and high-speed data transmission up to 480 Mbps.',
  '{"Current Output":"Up to 3.5A Fast Charge","Durability":"10000+ Bend Tested"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'chhena-poda-fresh',
  'khandagiri-sweets',
  'Traditional Odisha Chhena Poda (Baked Cottage Cheese)',
  'Khandagiri Heritage',
  '500 g',
  190,
  200,
  5,
  'restaurants',
  'Traditional Sweets',
  true,
  4.9,
  340,
  true,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
  'Authentic Odia dessert made by slow baking fresh cottage cheese, caramelized sugar, cardamom, and roasted cashews. Soft interior with aromatic caramelized brown crust.',
  '{"Specialty":"State Sweet of Odisha","Shelf Life":"3 Days"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'volini-pain-spray-100g',
  'sum-medico',
  'Volini Instant Pain Relief Spray',
  'Sun Pharma',
  '100 g',
  165,
  185,
  11,
  'pharmacy',
  'Medicines',
  true,
  4.8,
  195,
  true,
  'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80',
  'Micro-particles formula for quick penetration and fast relief from joint pain, lower back pain, sprains, and sports muscle strains.',
  '{"Active Salt":"Diclofenac Diethylamine, Methyl Salicylate, Menthol","Form":"Aerosol Spray"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'pediasure-vanilla-400g',
  'sum-medico',
  'PediaSure 7+ Complete Nutrition Drink (Vanilla)',
  'Abbott',
  '400 g',
  395,
  430,
  8,
  'pharmacy',
  'Baby Nutrition',
  true,
  4.9,
  160,
  true,
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
  'Scientifically formulated with 37 vital nutrients, prebiotics, and zinc to support growing children''s immunity, bone health, and height gain.',
  '{"Flavor":"Classic Vanilla","Nutrients":"37 Vital Growth Nutrients"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'accu-chek-active-glucometer',
  'sum-medico',
  'Accu-Chek Active Blood Glucose Monitor Kit',
  'Roche',
  '1 Unit (with 10 Strips & Lancets)',
  899,
  1299,
  30,
  'pharmacy',
  'Patient Care',
  true,
  4.9,
  220,
  true,
  'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80',
  'Accurate, easy-to-use blood glucose monitoring system providing accurate readings in just 5 seconds. Doctor recommended for home and clinic care.',
  '{"Test Time":"5 Seconds","Warranty":"Lifetime Manufacturer Warranty"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
INSERT INTO public.products (
  id, shop_id, name, brand, quantity, price, original_price, discount_percent,
  category, store_category, in_stock, rating, reviews_count, popular, image,
  description, information
) VALUES (
  'dettol-sanitizer-500ml',
  'sum-medico',
  'Dettol Instant Germ Protection Hand Sanitizer Pump',
  'Dettol',
  '500 ml',
  195,
  225,
  13,
  'pharmacy',
  'Wellness',
  true,
  4.8,
  140,
  false,
  'https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=600&q=80',
  'Kills 99.9% of illness-causing germs without soap or water. Non-sticky formula enriched with moisturizers and fresh fragrance.',
  '{"Alcohol Content":"72% v/v","Format":"Pump Dispenser Bottle"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  shop_id = EXCLUDED.shop_id,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  quantity = EXCLUDED.quantity,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  category = EXCLUDED.category,
  store_category = EXCLUDED.store_category,
  in_stock = EXCLUDED.in_stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  popular = EXCLUDED.popular,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  information = EXCLUDED.information;
