INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'apna-pharmacy',
  'Apna Pharmacy & Surgicals',
  'pharmacy',
  'Medicines & Health',
  4.9,
  532,
  0.6,
  '0.6 km',
  'Jayadev Vihar',
  'Lane 3, Biju Patnaik College Road, Jayadev Vihar, Bhubaneswar',
  '15–25 min',
  10,
  true,
  'Open · Closes 11:00 PM',
  '11:00 PM',
  840,
  50,
  true,
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
  'Licensed neighborhood pharmacy stocked with genuine OTC healthcare essentials, fever relief, multivitamins, baby food, and medical supplies.',
  'Dr. Alok Nayak (Pharm)',
  '+91 94372 33445',
  '{"100% Genuine","Licensed","Fastest Delivery"}'::text[],
  '{"All","Medicines","Wellness","First Aid","Baby Care"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'odisha-stationery',
  'Odisha Stationery & Book House',
  'stationery',
  'Stationery & School Supplies',
  4.7,
  295,
  2,
  '2.0 km',
  'Chandrasekharpur',
  'Opposite Petrol Pump, Damana Square, Chandrasekharpur, Bhubaneswar',
  '25–35 min',
  20,
  true,
  'Open · Closes 9:00 PM',
  '9:00 PM',
  410,
  80,
  false,
  'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1507842229451-79b1be886a20?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
  'School notebooks, premium pens, art supplies, office folders, calculation tools, and engineering drawing sets for students and professionals.',
  'Manas Jena',
  '+91 98619 55667',
  '{"Student Friendly","School Supplies","Bulk Stationery"}'::text[],
  '{"All","Notebooks","Pens & Pencils","Art & Craft","Office Supplies"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'kumar-electronics',
  'Kumar Electronics & Mobiles',
  'electronics',
  'Electronics & Accessories',
  4.5,
  189,
  3.1,
  '3.1 km',
  'Nayapalli',
  'Near ISKCON Temple, Nayapalli, Bhubaneswar',
  '35–45 min',
  30,
  true,
  'Open · Closes 9:30 PM',
  '9:30 PM',
  160,
  200,
  false,
  'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
  'Original mobile phone chargers, Type-C cables, wired & wireless earphones, power banks, extension boards, and everyday tech gadgets.',
  'Santosh Kumar',
  '+91 97760 11223',
  '{"Brand Warranty","Original Goods","Tech Support"}'::text[],
  '{"All","Cables & Adapters","Audio","Power","Accessories"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'khandagiri-sweets',
  'Khandagiri Sweets & Chaat',
  'restaurants',
  'Traditional Sweets & Snacks',
  4.8,
  760,
  3.5,
  '3.5 km',
  'Khandagiri',
  'Square Junction, Near Caves Entrance, Khandagiri, Bhubaneswar',
  '25–35 min',
  25,
  false,
  'Closed · Opens 4:00 PM',
  '10:30 PM',
  120,
  100,
  false,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
  'Famous for traditional Odisha Chhena Poda, Rasagola, hot samosas, dahi vada aloo dum, and evening street chaat treats.',
  'Debasis Das',
  '+91 94388 77665',
  '{"Authentic Odia","Famous Chaat","Freshly Cooked"}'::text[],
  '{"All","Traditional Sweets","Evening Snacks","Chaat Special"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'sum-medico',
  'SUM Medico & Healthcare',
  'pharmacy',
  'Pharmacy & Patient Care',
  4.9,
  428,
  3.8,
  '3.8 km',
  'SUM Hospital, Kalinga Nagar',
  'Opposite Gate No. 2, IMS & SUM Hospital Road, Kalinga Nagar, Bhubaneswar',
  '20–30 min',
  20,
  true,
  'Open 24 Hours · Immediate Delivery',
  'Open 24x7',
  650,
  50,
  true,
  'https://images.unsplash.com/photo-1586015555751-63c299c855a8?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=200&q=80',
  'Serving IMS & SUM Hospital campus, doctors, medical staff, patients, and Kalinga Nagar residents 24x7. Stocked with genuine emergency medications, surgical items, baby nutrition, and wellness essentials.',
  'Debabrata Samantray',
  '+91 94371 88990',
  '{"24x7 Available","Opposite SUM Hospital","Emergency Care","Doctor Trusted"}'::text[],
  '{"All","Medicines","Wellness","Patient Care","Baby Nutrition"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

