INSERT INTO public.shops-- Shops

INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'sharma-grocery',
  'Sharma Grocery Store',
  'grocery',
  'Grocery & Household',
  4.7,
  486,
  0.8,
  '0.8 km',
  'Jayadev Vihar',
  'Plot 142, IRC Village Road, Jayadev Vihar, Bhubaneswar',
  '25–35 min',
  20,
  true,
  'Open · Closes 9:30 PM',
  '9:30 PM',
  520,
  100,
  true,
  'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
  'Serving the Jayadev Vihar community for over 18 years. Best quality daily grocery staples, authentic spices, cold-pressed oils, and household goods at honest neighborhood prices.',
  'Ramesh Sharma',
  '+91 94370 12345',
  '{"Verified Local","Instant UPI","Doorstep Delivery","Fresh Stock"}'::text[],
  '{"All","Grocery","Dairy & Bread","Beverages","Snacks","Household"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'maa-laxmi',
  'Maa Laxmi General Store',
  'grocery',
  'Grocery & Household',
  4.8,
  342,
  1.2,
  '1.2 km away',
  'Saheed Nagar',
  'Shop 18, Commercial Complex, Saheed Nagar, Bhubaneswar',
  '20–30 min',
  15,
  true,
  'Open · Closes 10:00 PM',
  '10:00 PM',
  360,
  80,
  true,
  'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  'A trusted family-run neighborhood shop offering premium pulses, rice, packaged dry fruits, gourmet biscuits, and daily domestic essentials.',
  'Subrat Mohanty',
  '+91 98612 87654',
  '{"Verified Local","350+ Products","Fast Delivery"}'::text[],
  '{"All","Grocery","Snacks","Household","Personal Care"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'fresh-basket',
  'Fresh Basket Organics',
  'fruits & vegetables',
  'Fresh Fruits & Farm Produce',
  4.9,
  624,
  1.5,
  '1.5 km',
  'Patia',
  'Near KIIT Campus 6 Road, Patia, Bhubaneswar',
  '20–30 min',
  25,
  true,
  'Open · Closes 8:30 PM',
  '8:30 PM',
  225,
  150,
  true,
  'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  'Direct farm sourced fresh seasonal vegetables, exotic salad greens, fresh herbs, and hand-picked orchard fruits. Washed and hygienically packaged.',
  'Priyadarshi Sahoo',
  '+91 99371 45678',
  '{"Organic Produce","Farm Direct","Chemical Free"}'::text[],
  '{"All","Daily Veggies","Exotic Fruits","Herbs & Greens"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;

INSERT INTO public.shops (
  id, name, category, category_label, rating, review_count, distance_km, distance_text,
  locality, address, delivery_time, delivery_fee, is_open, opening_hours, closes_at,
  product_count, min_order, featured, image, cover_image, avatar, description,
  owner_name, phone, tags, catalog_categories
) VALUES (
  'city-bakery',
  'City Bakery & Confectionery',
  'bakery',
  'Artisan Bakery & Fresh Bakes',
  4.6,
  418,
  2.4,
  '2.4 km',
  'Master Canteen',
  'Station Square, Master Canteen, Bhubaneswar',
  '30–40 min',
  25,
  true,
  'Open · Closes 10:30 PM',
  '10:30 PM',
  185,
  100,
  false,
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=1400&q=80',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  'Oven fresh breads, soft sandwich loaves, puffs, authentic cookies, milk cakes, and handcrafted celebration cakes made with pure butter.',
  'Bikash Tripathy',
  '+91 93380 99887',
  '{"Oven Fresh","Artisan","Freshly Baked"}'::text[],
  '{"All","Breads","Cakes & Pastries","Cookies","Savouries"}'::text[]
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  category_label = EXCLUDED.category_label,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  distance_km = EXCLUDED.distance_km,
  distance_text = EXCLUDED.distance_text,
  locality = EXCLUDED.locality,
  address = EXCLUDED.address,
  delivery_time = EXCLUDED.delivery_time,
  delivery_fee = EXCLUDED.delivery_fee,
  is_open = EXCLUDED.is_open,
  opening_hours = EXCLUDED.opening_hours,
  closes_at = EXCLUDED.closes_at,
  product_count = EXCLUDED.product_count,
  min_order = EXCLUDED.min_order,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  cover_image = EXCLUDED.cover_image,
  avatar = EXCLUDED.avatar,
  description = EXCLUDED.description,
  owner_name = EXCLUDED.owner_name,
  phone = EXCLUDED.phone,
  tags = EXCLUDED.tags,
  catalog_categories = EXCLUDED.catalog_categories;
